name: 'test php checkout'
description: 'php checkout'

runs:
  using: "composite"
  steps:

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: entrypoint.sh
      shell: bash